# Build a new github-release when release-tag is committed to the repository
# see https://github.com/marketplace/actions/gh-release
name: Release new version on github

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: 'See the [Changelog](https://github.com/JohannesSchorr/incremental-delaunay/blob/master/changelog.md)'